train:
  epochs: 100
  iterations: 300000
  batch_size: 8
  crop_size: 384
  learning_rate: 1e-4
  base_channels: 64
  num_res_blocks: 2
  beta_start: 0.0001
  beta_end: 0.02
  T: 100  # diffusion time steps
  save_every: 10000
  eval_every: 5000

paths:
  synthetic_data_root: "./data/synthetic"
  real_data_root: "./data/real"
  model_save_dir: "./checkpoints"
  log_dir: "./logs"
